---
- name: Setting up universe
  hosts: all
  become: true
  become_user: root
  
  roles:
    - role: ssh
      tags: ssh
    
    - role: m4rcu5nl.zerotier-one
      tags: zerotier


- name: Clustering Consul
  hosts: consul
  become: true
  become_user: root

  roles:
    - role: consul
      tags: consul 
