---
- name: Setting up universe
  hosts: all
  become: true
  become_user: root
 
  roles:
    - role: ssh
      tags: ssh
    
    - role: m4rcu5nl.zerotier-one
      tags: zerotier


- name: Clustering Consul
  hosts: consul-server
  become: true
  become_user: root

  roles:
    - role: consul
      tags: consul 
  
- name: Clustering Nomad
  hosts: nomad
  become: true
  become_user: root

  roles:
    - role: brianshumate.nomad
      tags: nomad

