---
- name: Updating the System
  hosts: all
  become: true
  apt: 
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Set authorized keys taken from url
  authorized_key:
    manage_dir: yes
    user: "{{ ansible_user }}"
    state: present
    key: https://github.com/{{ item }}.keys
  with_items: "{{gitusername}}"

- name: Revoke old users
  authorized_key:
    user: "{{ ansible_user }}"
    state: absent
    key: https://github.com/{{ item }}.keys
  with_items: "{{revokeuser}}"

- lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^ubuntu ALL='
    line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'

